name: Deploy Admin to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'admin/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'admin/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-admin"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'admin/package-lock.json'

      - name: Install dependencies
        working-directory: ./admin
        run: npm ci

      - name: Build project
        working-directory: ./admin
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload admin artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './admin/dist'

  deploy:
    environment:
      name: github-pages-admin
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
